---

# Default network for pod
#       values: flannel
default_network: flannel

# CNI-multiplexer to use
#       values: multus
cni_multiplexer: multus

# Container Network to benchmark
#       values: ovs
container_network: ovs

# C-VNF(Containerized VNF) to use as workload
#       values: debug
c_vnf: debug