apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-net
  namespace: default
  # annotations:
  #   k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/vsperf-br
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "vsperf-br"
    }'
