apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: ovs-net, ovs-net
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
        - containerPort: 80


